# Generated by Django 5.2.3 on 2026-08-03 16:18

import coding.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chat_archived'),
        ('coding', '0002_feature_delegations'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=1024, upload_to=coding.models.managed_file_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='application/octet-stream', max_length=255)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_files', to='chat.chatmessage')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='coding.codingsession')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='coding.codingturn')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='coding_file_session_idx')],
            },
        ),
    ]
