# Generated by Django 5.2.3 on 2026-08-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0003_managedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfile',
            name='delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='coding.featuredelegation'),
        ),
    ]
