"""
Django settings for CorvAI project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from urllib.parse import urlparse
from dotenv import load_dotenv

# Load .env values (including APP_ACCESS_TOKEN) early
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CORV_PUBLIC_BASE_URL = os.getenv("CORV_PUBLIC_BASE_URL", "").rstrip("/")


def _resolve_log_file(filename: str) -> str:
    """Return a writable log path, falling back to /tmp when project root isn't writable."""
    primary = os.path.join(BASE_DIR, filename)
    try:
        if os.path.exists(primary):
            if os.access(primary, os.W_OK):
                return primary
        else:
            parent = os.path.dirname(primary) or "."
            if os.access(parent, os.W_OK):
                return primary
    except Exception:
        pass

    fallback_dir = os.getenv("CORV_LOG_DIR", "/tmp")
    try:
        os.makedirs(fallback_dir, exist_ok=True)
    except Exception:
        fallback_dir = "/tmp"
    return os.path.join(fallback_dir, filename)


def _resolve_media_root() -> str:
    """Return a writable media root, falling back when the project media dir is root-owned."""
    configured = os.getenv("CORV_MEDIA_DIR", os.path.join(BASE_DIR, "media"))
    candidates = [
        configured,
        os.path.join(BASE_DIR, ".media"),
        os.path.join("/tmp", "corvai-media"),
    ]
    for candidate in candidates:
        try:
            os.makedirs(candidate, exist_ok=True)
            if os.access(candidate, os.W_OK):
                return candidate
        except Exception:
            continue
    return os.path.join("/tmp", "corvai-media")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(ge2777wrfkdq@ak#@n^sx^+8^6yz2v*78gy5h6f$+^de4e6p9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Simple app-wide access token (optional). Used by AccessTokenMiddleware.
APP_ACCESS_TOKEN = os.getenv("APP_ACCESS_TOKEN", "")


BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"
MEDIA_ROOT = _resolve_media_root()
# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'Corv.apps.CorvConfig',
    'input',
    'api',
    'chat',
    'orchestration.apps.OrchestrationConfig',
    'study.apps.StudyConfig',
    'workout.apps.WorkoutConfig',
    'ssh_connections.apps.SshConnectionsConfig',
    'coding.apps.CodingConfig',
    'openai_integration',
]

CORV_CODING_DIR = os.getenv("CORV_CODING_DIR", "/var/lib/corv-coding")
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("CORV_MAX_UPLOAD_SIZE", str(100 * 1024 * 1024)))

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Corv.middleware.AccessTokenMiddleware',
]

ROOT_URLCONF = 'CorvAI.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CorvAI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _database_settings():
    db_url = os.getenv("DATABASE_URL")
    if not db_url:
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    parsed = urlparse(db_url)
    scheme = (parsed.scheme or "").lower()

    if scheme in ("postgres", "postgresql"):
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed.path.lstrip("/") or "",
            'USER': parsed.username or "",
            'PASSWORD': parsed.password or "",
            'HOST': parsed.hostname or "",
            'PORT': str(parsed.port or ""),
        }

    if scheme in ("sqlite", "sqlite3"):
        # Allow sqlite:///relative/path.db or sqlite:////abs/path.db
        name = parsed.path or (BASE_DIR / 'db.sqlite3')
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': name,
        }

    # Fallback to default sqlite if scheme is unrecognized
    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


DATABASES = {
    'default': _database_settings()
}

# Keep Celery's Redis result backend bounded. Worker process recycling and hard
# container limits are configured in docker-compose.yml.
CELERY_RESULT_EXPIRES = int(os.getenv("CELERY_RESULT_EXPIRES", "3600"))
CELERY_WORKER_PREFETCH_MULTIPLIER = int(os.getenv("CELERY_WORKER_PREFETCH_MULTIPLIER", "1"))


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Simple file logging for call monitoring
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "simple": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"},
    },
    "handlers": {
        "call_monitor_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": _resolve_log_file("call_monitor.log"),
            "formatter": "simple",
        },
        "fcm_push_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": _resolve_log_file("fcm_push.log"),
            "formatter": "simple",
        },
        "call_sessions_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": _resolve_log_file("call_sessions.log"),
            "formatter": "simple",
        },
    },
    "loggers": {
        "orchestration": {
            "handlers": ["call_monitor_file"],
            "level": "INFO",
            "propagate": True,
        },
        "orchestration.notifications": {
            "handlers": ["fcm_push_file"],
            "level": "INFO",
            "propagate": False,
        },
        "orchestration.call_processing": {
            "handlers": ["call_sessions_file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Celery configuration
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = os.getenv("TIME_ZONE", TIME_ZONE)
CELERY_BEAT_SCHEDULE = {
    "cleanup-expired-notes": {
        "task": "orchestration.tasks.cleanup_expired_notes",
        "schedule": 300.0,  # every 5 minutes
    },
    "poll-soft-events": {
        "task": "orchestration.tasks.poll_soft_events_task",
        "schedule": 300.0,  # every 5 minutes
    },
    "poll-soft-event-slots": {
        "task": "orchestration.tasks.poll_soft_event_slots_task",
        "schedule": 300.0,  # every 5 minutes
    },
    "poll-scheduled-tasks": {
        "task": "orchestration.tasks.poll_scheduled_tasks",
        "schedule": 60.0,  # every minute
    },
    "poll-call-sessions": {
        "task": "orchestration.tasks.poll_call_sessions",
        "schedule": 15.0,  # every 15 seconds
    },
}

# User-triggered location-note geocoding; override to switch providers/self-host.
NOMINATIM_BASE_URL = os.getenv("NOMINATIM_BASE_URL", "https://nominatim.openstreetmap.org")
