# Generated by Django 5.2.3 on 2026-05-16 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0005_chat_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('term_start_date', models.DateField(blank=True, null=True)),
                ('term_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_courses', to='chat.chat')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StudyExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('quiz', 'Quiz'), ('practical', 'Practical'), ('other', 'Other')], default='other', max_length=32)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('weight', models.FloatField(default=1.0)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='study.studycourse')),
            ],
            options={
                'ordering': ['scheduled_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('plan_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.CharField(blank=True, default='system', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='study.studycourse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('estimated_effort_minutes', models.PositiveIntegerField(default=60)),
                ('weight', models.FloatField(default=1.0)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('review', 'Review'), ('mastered', 'Mastered')], default='not_started', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='study.studycourse')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_topics', to='study.studytopic')),
            ],
            options={
                'ordering': ['course', 'order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudySessionTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_date', models.DateField()),
                ('target_preferred_minutes', models.PositiveIntegerField(default=60)),
                ('target_min_minutes', models.PositiveIntegerField(default=30)),
                ('focus', models.TextField(blank=True, default='')),
                ('outcome', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed'), ('canceled', 'Canceled')], default='planned', max_length=32)),
                ('soft_event_ref', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_targets', to='study.studycourse')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_targets', to='study.studyexam')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_targets', to='study.studyplan')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_targets', to='study.studytopic')),
            ],
            options={
                'ordering': ['target_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudySessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('soft_event_ref', models.UUIDField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('actual_minutes', models.PositiveIntegerField(default=0)),
                ('self_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('completed', 'Completed'), ('partial', 'Partial'), ('skipped', 'Skipped')], default='partial', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='study.studycourse')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='study.studyexam')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='study.studyplan')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='study.studysessiontarget')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='study.studytopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('lecture_pdf', 'Lecture PDF'), ('slides', 'Slides'), ('past_exam', 'Past Exam'), ('notes', 'Notes'), ('link', 'Link'), ('other', 'Other')], default='other', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, default='')),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('ingestion_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('raw_text', models.TextField(blank=True, default='')),
                ('parsed_text', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='study.studycourse')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='study.studyexam')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='study.studytopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('evidence_count', models.PositiveIntegerField(default=0)),
                ('last_evidence_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_entries', to='study.studycourse')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_entries', to='study.studytopic')),
            ],
            options={
                'ordering': ['course', 'topic'],
            },
        ),
        migrations.AddIndex(
            model_name='studycourse',
            index=models.Index(fields=['status'], name='study_study_status_dd9989_idx'),
        ),
        migrations.AddIndex(
            model_name='studycourse',
            index=models.Index(fields=['code'], name='study_study_code_fae4db_idx'),
        ),
        migrations.AddIndex(
            model_name='studyexam',
            index=models.Index(fields=['course', 'kind'], name='study_study_course__654981_idx'),
        ),
        migrations.AddIndex(
            model_name='studyexam',
            index=models.Index(fields=['scheduled_at'], name='study_study_schedul_28d0ae_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['course', 'status'], name='study_study_course__f13b09_idx'),
        ),
        migrations.AddIndex(
            model_name='studyplan',
            index=models.Index(fields=['window_start', 'window_end'], name='study_study_window__937758_idx'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('course',), name='unique_active_study_plan_per_course'),
        ),
        migrations.AddIndex(
            model_name='studytopic',
            index=models.Index(fields=['course', 'order_index'], name='study_study_course__223650_idx'),
        ),
        migrations.AddIndex(
            model_name='studytopic',
            index=models.Index(fields=['status'], name='study_study_status_140a9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='studytopic',
            constraint=models.UniqueConstraint(fields=('course', 'name'), name='unique_topic_per_course'),
        ),
        migrations.AddIndex(
            model_name='studysessiontarget',
            index=models.Index(fields=['plan', 'target_date'], name='study_study_plan_id_09ef95_idx'),
        ),
        migrations.AddIndex(
            model_name='studysessiontarget',
            index=models.Index(fields=['status'], name='study_study_status_971d7b_idx'),
        ),
        migrations.AddIndex(
            model_name='studysessiontarget',
            index=models.Index(fields=['course', 'target_date'], name='study_study_course__4c206a_idx'),
        ),
        migrations.AddIndex(
            model_name='studysessionlog',
            index=models.Index(fields=['course', 'created_at'], name='study_study_course__6c6f8e_idx'),
        ),
        migrations.AddIndex(
            model_name='studysessionlog',
            index=models.Index(fields=['result'], name='study_study_result_131326_idx'),
        ),
        migrations.AddIndex(
            model_name='studysessionlog',
            index=models.Index(fields=['topic', 'created_at'], name='study_study_topic_i_e2c377_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['course', 'kind'], name='study_study_course__decbf9_idx'),
        ),
        migrations.AddIndex(
            model_name='studymaterial',
            index=models.Index(fields=['ingestion_status'], name='study_study_ingesti_94f5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['course', 'topic'], name='study_topic_course__0fd7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='topicmastery',
            index=models.Index(fields=['mastery_score'], name='study_topic_mastery_0611fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='topicmastery',
            constraint=models.UniqueConstraint(fields=('course', 'topic'), name='unique_topic_mastery_per_course'),
        ),
    ]
