# Generated by Django 5.2.3 on 2026-05-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='study/materials/'),
        ),
    ]
