# Generated by Django 5.2.3 on 2026-05-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_studymaterial_uploaded_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='converted_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='processing_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='solved_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='theory_markdown',
            field=models.TextField(blank=True, default=''),
        ),
    ]
