# Generated by Django 5.2.3 on 2026-05-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_update_material_kind_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytopic',
            name='summary',
            field=models.TextField(blank=True, default='', help_text="Human-readable bullet-point summary of what's covered in this topic"),
        ),
    ]
