# Generated by Django 5.2.3 on 2026-05-19 21:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_studytopic_homework'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField()),
                ('material_text', models.TextField(blank=True, default='', help_text='Converted markdown from uploaded PDF or material')),
                ('plan', models.TextField(blank=True, default='', help_text='LLM-generated approach/strategy for the assignment')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='Array of step objects: [{step_number, title, description}, ...]')),
                ('session_count', models.PositiveIntegerField(default=1, help_text='Number of sessions to break assignment into')),
                ('soft_event_refs', models.JSONField(blank=True, default=list, help_text='List of soft event IDs created for this assignment')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='draft', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='study.studycourse')),
            ],
            options={
                'ordering': ['-due_at', '-created_at'],
                'indexes': [models.Index(fields=['course', 'status'], name='study_study_course__07002e_idx'), models.Index(fields=['due_at'], name='study_study_due_at_912d32_idx'), models.Index(fields=['status'], name='study_study_status_4e5ece_idx')],
            },
        ),
    ]
