# Generated by Django 5.2.3 on 2026-09-02 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_studytopicaudiobookversion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studytopicaudiobookversion',
            new_name='study_study_topic_i_b87656_idx',
            old_name='study_study_topic_idx',
        ),
        migrations.RenameIndex(
            model_name='studytopicaudiobookversion',
            new_name='study_study_status_617f8d_idx',
            old_name='study_study_status_0d468d_idx',
        ),
    ]
