# Generated by Django 5.2.3 on 2025-12-29 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0003_alter_chat_nickname_alter_chatmessage_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='orchestrati_slug_9994b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToolFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manifest_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('params_schema', models.JSONField(blank=True, default=dict)),
                ('return_schema', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('deprecated', models.BooleanField(default=False)),
                ('handler_ref', models.CharField(help_text='Python dotted path or registry key resolved by the Function Runner.', max_length=255)),
                ('embedding', models.JSONField(blank=True, default=None, help_text='Optional vector representation for retrieval.', null=True)),
                ('examples', models.JSONField(blank=True, default=list, help_text='List of example {user_prompt, params} objects for better matching.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='orchestration.toolmodule')),
            ],
            options={
                'ordering': ['manifest_id'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, default='', help_text='UI session/window identifier.', max_length=255)),
                ('trace_id', models.CharField(blank=True, default='', help_text='Correlation id across layers.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('waiting_on_user', 'Waiting on User'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=32)),
                ('progress', models.FloatField(default=0.0)),
                ('user_visible_summary', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('cancel_requested', models.BooleanField(default=False)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='chat.chat')),
                ('active_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_jobs', to='orchestration.toolfunction')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='orchestration.toolmodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, default='', help_text='Which layer emitted the event (frontman/caller/runner).', max_length=32)),
                ('event_type', models.CharField(choices=[('info', 'Info'), ('progress', 'Progress'), ('error', 'Error'), ('state_change', 'State Change')], default='info', max_length=32)),
                ('visibility', models.CharField(choices=[('user_visible', 'User Visible'), ('tool_only', 'Tool Only'), ('system_note', 'System Note')], default='system_note', max_length=32)),
                ('message', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('call_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orchestration.job')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['job', 'created_at'], name='orchestrati_job_id_44b070_idx'), models.Index(fields=['visibility'], name='orchestrati_visibil_3fe46c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='toolfunction',
            index=models.Index(fields=['manifest_id'], name='orchestrati_manifes_81a20b_idx'),
        ),
        migrations.AddIndex(
            model_name='toolfunction',
            index=models.Index(fields=['module', 'deprecated'], name='orchestrati_module__7885a8_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='orchestrati_status_429255_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['session_id'], name='orchestrati_session_bf2c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['trace_id'], name='orchestrati_trace_i_cb3e29_idx'),
        ),
    ]
