# Generated by Django 5.2.3 on 2026-01-03 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0012_soft_events_module'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orchestrationsetting',
            new_name='orchestrati_key_5b0ae4_idx',
            old_name='orchestrati_key_5f2c2b_idx',
        ),
        migrations.RenameIndex(
            model_name='softevent',
            new_name='orchestrati_status_2553b3_idx',
            old_name='orch_softevent_status_idx',
        ),
        migrations.RenameIndex(
            model_name='softevent',
            new_name='orchestrati_soft_de_02f308_idx',
            old_name='orch_softevent_soft_deadline_idx',
        ),
        migrations.RenameIndex(
            model_name='softevent',
            new_name='orchestrati_hard_de_728e76_idx',
            old_name='orch_softevent_hard_deadline_idx',
        ),
        migrations.RenameIndex(
            model_name='softevent',
            new_name='orchestrati_priorit_9da380_idx',
            old_name='orch_softevent_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='softeventslot',
            new_name='orchestrati_start_a_4cd03e_idx',
            old_name='orch_softeventslot_start_idx',
        ),
        migrations.RenameIndex(
            model_name='softeventslot',
            new_name='orchestrati_status_1451bc_idx',
            old_name='orch_softeventslot_status_idx',
        ),
        migrations.RenameIndex(
            model_name='softeventslot',
            new_name='orchestrati_notify__303825_idx',
            old_name='orch_softeventslot_notify_idx',
        ),
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='orchestrati_created_6b984b_idx',
            old_name='orchestrati_created_f4c7bf_idx',
        ),
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='orchestrati_source_d43e38_idx',
            old_name='orchestrati_source_d9b56a_idx',
        ),
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='orchestrati_model_8b8ce3_idx',
            old_name='orchestrati_model_34cf3a_idx',
        ),
        migrations.RenameIndex(
            model_name='usernote',
            new_name='orchestrati_user_id_746f7e_idx',
            old_name='orchestrati_user_id_5765e3_idx',
        ),
        migrations.RenameIndex(
            model_name='usernote',
            new_name='orchestrati_deleted_2d386b_idx',
            old_name='orchestrati_deleted_5fb17e_idx',
        ),
        migrations.AlterField(
            model_name='softevent',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='softeventslot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
