# Generated by Django 5.2.3 on 2026-01-15 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0028_calendar_manager_get_soft_event'),
        ('orchestration', '0028_messages_module'),
    ]

    operations = [
    ]
