# Generated by Django 5.2.3 on 2026-05-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0038_softeventslot_call_made_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='callsession',
            new_name='orchestrati_status_242133_idx',
            old_name='orchestration_status_8b2923_idx',
        ),
        migrations.RenameIndex(
            model_name='callsession',
            new_name='orchestrati_status_ab8bc5_idx',
            old_name='orchestration_status_550906_idx',
        ),
        migrations.RenameIndex(
            model_name='calltranscriptentry',
            new_name='orchestrati_session_6ccfdf_idx',
            old_name='orchestration_session_5b2d09_idx',
        ),
        migrations.RenameIndex(
            model_name='pushtoken',
            new_name='orchestrati_platfor_291b94_idx',
            old_name='orchestration_platform_6ffbcb_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledtask',
            new_name='orchestrati_status_72d89b_idx',
            old_name='orchestration_status_8b7f4d_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledtask',
            new_name='orchestrati_is_runn_39d7bb_idx',
            old_name='orchestration_is_runn_e8d9f3_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledtasklogentry',
            new_name='orchestrati_run_id_fac085_idx',
            old_name='orchestration_run_id_2f0cbb_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledtaskrun',
            new_name='orchestrati_task_id_d82c7f_idx',
            old_name='orchestration_task_id_335ae6_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledtaskrun',
            new_name='orchestrati_status_94887f_idx',
            old_name='orchestration_status_1df5c6_idx',
        ),
        migrations.RenameIndex(
            model_name='softeventslot',
            new_name='orchestrati_call_ma_234af1_idx',
            old_name='orchestration_softeventslot_call_made_at_idx',
        ),
        migrations.RenameIndex(
            model_name='usermessage',
            new_name='orchestrati_created_e26ae5_idx',
            old_name='orchestration_created_66b9cd_idx',
        ),
        migrations.RenameIndex(
            model_name='usermessage',
            new_name='orchestrati_read_at_e00a31_idx',
            old_name='orchestration_read_at_ebd22b_idx',
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='active', max_length=16),
        ),
    ]
