# Generated by Django 5.2.3 on 2026-06-03 21:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0042_soft_slot_outcome_functions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardEventTaskLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=255)),
                ('event_title', models.CharField(blank=True, default='', max_length=255)),
                ('event_start_raw', models.CharField(blank=True, default='', max_length=64)),
                ('event_end_raw', models.CharField(blank=True, default='', max_length=64)),
                ('event_start_at', models.DateTimeField()),
                ('event_end_at', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='google_calendar', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_event_links', to='orchestration.objectivetask')),
            ],
            options={
                'ordering': ['event_start_at', 'created_at'],
                'indexes': [models.Index(fields=['task'], name='orchestrati_task_id_02b788_idx'), models.Index(fields=['event_id', 'event_start_at'], name='orchestrati_event_i_ad4d8a_idx'), models.Index(fields=['event_start_at'], name='orchestrati_event_s_d797b8_idx')],
                'constraints': [models.UniqueConstraint(fields=('task', 'event_id', 'event_start_raw', 'event_end_raw'), name='unique_hard_event_task_link')],
            },
        ),
    ]
