# Generated by Django 5.2.3 on 2026-08-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0065_internet_search_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('key', models.CharField(default='default', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('altitude_m', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('timezone_name', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='device', max_length=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
