# Generated by Django 5.2.3 on 2026-08-10 09:46

import django.contrib.postgres.fields
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0066_user_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, default='default', max_length=255)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('search_text', models.TextField(blank=True, default='')),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=64), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['entity_type', 'name'],
                'indexes': [models.Index(fields=['user_id', 'entity_type', 'name'], name='orchestrati_user_id_347d4d_idx'), models.Index(fields=['deleted_at'], name='orchestrati_deleted_72579e_idx')],
            },
        ),
    ]
