from django.db import migrations

FUNCTIONS = [('user_info.create_location', 'Create location', 'Create a structured location with coordinates, description, extensible attributes, and unified tags.', 'orchestration.tools.user_info.create_location'), ('user_info.update_location', 'Update location', 'Update a location by exact ID and refresh semantic search.', 'orchestration.tools.user_info.update_location'), ('user_info.delete_location', 'Delete location', 'Soft-delete a location by exact ID.', 'orchestration.tools.user_info.delete_location'), ('user_info.list_locations', 'List/search locations', 'List locations or semantically search only locations.', 'orchestration.tools.user_info.list_locations'), ('user_info.create_person', 'Create person', 'Create a person with relationship, description, facts, extensible attributes, and unified tags.', 'orchestration.tools.user_info.create_person'), ('user_info.update_person', 'Update person', 'Update a person by exact ID and refresh semantic search.', 'orchestration.tools.user_info.update_person'), ('user_info.delete_person', 'Delete person', 'Soft-delete a person by exact ID.', 'orchestration.tools.user_info.delete_person'), ('user_info.list_people', 'List/search people', 'List people or semantically search only people.', 'orchestration.tools.user_info.list_people'), ('user_info.get_entity', 'Get knowledge entity', 'Read one structured knowledge entity by exact ID.', 'orchestration.tools.user_info.get_entity'), ('user_info.search_knowledge', 'Search knowledge', 'General semantic search across notes, locations, people, and future typed entities with unified tags and type-aware ranking.', 'orchestration.tools.user_info.search_knowledge')]
PARAMS = {'user_info.create_location': {'type': 'object', 'properties': {'name': {'type': 'string'}, 'latitude': {'type': 'number'}, 'longitude': {'type': 'number'}, 'description': {'type': 'string'}, 'tags': {'type': 'array', 'items': {'type': 'string'}}, 'attributes': {'type': 'object'}}, 'required': ['name', 'latitude', 'longitude']}, 'user_info.update_location': {'type': 'object', 'properties': {'location_id': {'type': 'string'}, 'name': {'type': 'string'}, 'latitude': {'type': 'number'}, 'longitude': {'type': 'number'}, 'description': {'type': 'string'}, 'tags': {'type': 'array', 'items': {'type': 'string'}}, 'attributes': {'type': 'object'}}, 'required': ['location_id']}, 'user_info.delete_location': {'type': 'object', 'properties': {'location_id': {'type': 'string'}}, 'required': ['location_id']}, 'user_info.list_locations': {'type': 'object', 'properties': {'query': {'type': 'string'}, 'tags': {'type': 'array', 'items': {'type': 'string'}}, 'limit': {'type': 'integer'}}}, 'user_info.create_person': {'type': 'object', 'properties': {'name': {'type': 'string'}, 'relationship': {'type': 'string'}, 'description': {'type': 'string'}, 'facts': {'type': 'array', 'items': {'type': 'string'}}, 'tags': {'type': 'array', 'items': {'type': 'string'}}, 'attributes': {'type': 'object'}}, 'required': ['name']}, 'user_info.update_person': {'type': 'object', 'properties': {'person_id': {'type': 'string'}, 'name': {'type': 'string'}, 'relationship': {'type': 'string'}, 'description': {'type': 'string'}, 'facts': {'type': 'array', 'items': {'type': 'string'}}, 'tags': {'type': 'array', 'items': {'type': 'string'}}, 'attributes': {'type': 'object'}}, 'required': ['person_id']}, 'user_info.delete_person': {'type': 'object', 'properties': {'person_id': {'type': 'string'}}, 'required': ['person_id']}, 'user_info.list_people': {'type': 'object', 'properties': {'query': {'type': 'string'}, 'tags': {'type': 'array', 'items': {'type': 'string'}}, 'limit': {'type': 'integer'}}}, 'user_info.get_entity': {'type': 'object', 'properties': {'entity_id': {'type': 'string'}}, 'required': ['entity_id']}, 'user_info.search_knowledge': {'type': 'object', 'properties': {'query': {'type': 'string'}, 'tags': {'type': 'array', 'items': {'type': 'string'}}, 'limit': {'type': 'integer'}}, 'required': ['query']}}
GUIDANCE = """Use plain user_info.add_note/update_note/delete_note for unstructured free-text notes exactly as before. Use structured locations for places that have coordinates, and structured people for relationship/facts that benefit from fields. Before updating or deleting, list/search and use the exact entity ID. Use list_locations or list_people for type-specific browsing. Use search_knowledge for general recall: it searches plain notes and every structured type with unified tags and vector semantics, prioritizing a likely type (for example locations for home/address/where queries) before broadening. Do not duplicate structured facts into plain notes unless the user explicitly asks. New structured types extend the shared KnowledgeEntity storage and search contract rather than requiring a new search silo."""

def configure(apps,schema_editor):
    Module=apps.get_model("orchestration","ToolModule"); Function=apps.get_model("orchestration","ToolFunction"); module,_=Module.objects.get_or_create(slug="user_info",defaults={"name":"User info","description":"","tags":[],"caller_instructions":""})
    module.description="Core profile, plain notes, and structured typed knowledge with unified tags and semantic search."
    module.caller_instructions=GUIDANCE
    module.tags=list(dict.fromkeys([*(module.tags or []),"knowledge","semantic-search","locations","people"]))
    module.save(update_fields=["description","caller_instructions","tags","updated_at"])
    for manifest,name,description,handler in FUNCTIONS:
        Function.objects.update_or_create(manifest_id=manifest,defaults={"module":module,"name":name,"description":description,"params_schema":PARAMS[manifest],"return_schema":{},"handler_ref":handler,"tags":["knowledge"],"deprecated":False})

def remove(apps,schema_editor): apps.get_model("orchestration","ToolFunction").objects.filter(manifest_id__in=[row[0] for row in FUNCTIONS]).delete()

class Migration(migrations.Migration):
    dependencies=[("orchestration","0067_structured_knowledge_entities")]
    operations=[migrations.RunPython(configure,remove)]
