# Generated by Django 5.2.3 on 2025-08-15 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_nickname_alter_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='nickname',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=models.TextField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
