# Generated by Django 5.2.3 on 2025-12-29 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_nickname_alter_chatmessage_id'),
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='audience',
            field=models.CharField(choices=[('user', 'User'), ('ai_stack', 'AI Stack')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='call_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='orchestration.job'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('user_visible', 'User Visible'), ('tool_only', 'Tool Only'), ('system_note', 'System Note'), ('error', 'Error')], default='user_visible', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='trace_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
