# Generated by Django 5.2.3 on 2025-11-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_options_chat_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
