# Generated by Django 5.2.3 on 2025-11-11 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0004_alter_chat_options_chat_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('mission', models.TextField(blank=True)),
                ('system_prompt', models.TextField()),
                ('style_guidelines', models.JSONField(blank=True, default=list)),
                ('closing_phrase', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCPModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('knowledge_requirements', models.JSONField(blank=True, default=list)),
                ('result_description', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='mcp.mcpmodule')),
            ],
            options={
                'unique_together': {('module', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='FunctionExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=16)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_logs', to='chat.chat')),
                ('function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcp.modulefunction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('awaiting_info', 'Awaiting Info'), ('ready', 'Ready'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='idle', max_length=32)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('missing_information', models.JSONField(blank=True, default=list)),
                ('last_error', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_plans', to='chat.chat')),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcp.assistantpersona')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ModuleFunctionErrorPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('handling_notes', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warn', 'Warn'), ('error', 'Error')], default='error', max_length=32)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_policies', to='mcp.modulefunction')),
            ],
            options={
                'unique_together': {('function', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ModuleFunctionParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('data_type', models.CharField(default='string', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('allowed_values', models.JSONField(blank=True, default=list)),
                ('example', models.CharField(blank=True, max_length=255)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='mcp.modulefunction')),
            ],
            options={
                'unique_together': {('function', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PersonaUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('goals', models.JSONField(blank=True, default=list)),
                ('preferences', models.JSONField(blank=True, default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='mcp.assistantpersona')),
            ],
            options={
                'unique_together': {('persona', 'profile_id')},
            },
        ),
    ]
