import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Notifications from "expo-notifications";
import * as Speech from "expo-speech";
import { Audio } from "expo-av";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { fetchActiveWorkoutSessions, fetchWorkoutPlans, fetchWorkoutSpeech, finishWorkoutSession, startWorkoutSession, updateWorkoutSessionItem, updateWorkoutSessionState, updateWorkoutSet } from "./api";
import type { WorkoutPlan, WorkoutSession } from "../../shared/types";

const RUNNER_KEY="corv.activeWorkoutRunner";
function targetText(target:Record<string,unknown>){return [target.reps&&`${target.reps} reps`,target.weight_kg&&`${target.weight_kg} kg`,target.duration_seconds&&`${target.duration_seconds}s`,target.distance_km&&`${target.distance_km} km`].filter(Boolean).join(" · ")||"Complete the set"}

export default function WorkoutScreen(){
  const [plans,setPlans]=useState<WorkoutPlan[]>([]),[sessions,setSessions]=useState<WorkoutSession[]>([]),[loading,setLoading]=useState(true),[now,setNow]=useState(Date.now());
  const refresh=useCallback(async()=>{try{const [p,a]=await Promise.all([fetchWorkoutPlans(),fetchActiveWorkoutSessions()]);setPlans(p.plans);setSessions(a.sessions)}catch(error:any){Alert.alert("Workout",error?.message||"Unable to load workouts")}finally{setLoading(false)}},[]);
  useEffect(()=>{void refresh();const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[refresh]);
  useEffect(()=>{AsyncStorage.setItem(RUNNER_KEY,JSON.stringify(sessions.map(item=>({id:item.id,status:item.status,updated_at:new Date().toISOString()})))).catch(()=>undefined)},[sessions]);
  const active=sessions[0];
  const next=useMemo(()=>active?.exercises.find(row=>!row.completed),[active]);
  const currentSet=next?.set_logs.find(item=>item.status==="active")||next?.set_logs.find(item=>item.status==="pending");
  const deadline=Number((currentSet?.actual||{}).deadline_ms||0); const remaining=deadline?Math.max(0,Math.ceil((deadline-now)/1000)):Number(currentSet?.target.duration_seconds||0);
  useEffect(()=>{if(!active||active.mode!=="guided"||active.guidance_level!=="full"||!deadline)return;if(remaining<=10&&remaining>0){Notifications.scheduleNotificationAsync({content:{title:`${remaining}`,body:next?.exercise.name||"Workout",sound:true},trigger:null}).catch(()=>undefined)}},[remaining,deadline,active?.id]);
  async function speak(text:string){await Audio.setAudioModeAsync({playsInSilentModeIOS:true,staysActiveInBackground:true,shouldDuckAndroid:true});const key=`workout.voice.${text.toLowerCase().replace(/[^a-z0-9]+/g,"-").slice(0,80)}`;try{let encoded=await AsyncStorage.getItem(key);if(!encoded){encoded=(await fetchWorkoutSpeech(text)).audio_base64;await AsyncStorage.setItem(key,encoded)}const {sound}=await Audio.Sound.createAsync({uri:`data:audio/mpeg;base64,${encoded}`},{shouldPlay:true});sound.setOnPlaybackStatusUpdate(status=>{if(status.isLoaded&&status.didJustFinish)void sound.unloadAsync()})}catch{Speech.stop();Speech.speak(text,{rate:.92,pitch:1.0})}}
  async function start(plan:WorkoutPlan,dayId:string,mode:"checklist"|"guided",guidance:"minimal"|"full"){await Notifications.requestPermissionsAsync();const item=await startWorkoutSession({plan:plan.id,planned_session:dayId||undefined,mode,guidance_level:guidance});setSessions([item]);if(mode==="guided"&&guidance==="full")void speak(`Starting ${item.title}. ${item.exercises[0]?.exercise.name||"First exercise"} is next.`)}
  async function startTimedSet(){if(!active||!next||!currentSet)return;const seconds=Number(currentSet.target.duration_seconds||next.duration_seconds||30);const item=await updateWorkoutSet(currentSet.id,{status:"active",actual:{...currentSet.actual,deadline_ms:Date.now()+seconds*1000}});setSessions(items=>items.map(s=>s.id===active.id?{...s,exercises:s.exercises.map(row=>row.id===item.id?item:row)}:s));if(active.guidance_level==="full")void speak(`Now ${next.exercise.name} for ${seconds} seconds.`)}
  async function completeSet(skip=false){if(!active||!next||!currentSet)return;const item=await updateWorkoutSet(currentSet.id,{status:skip?"skipped":"completed",actual:{...currentSet.target,...currentSet.actual}});const updated={...active,exercises:active.exercises.map(row=>row.id===item.id?item:row)};setSessions([updated]);const following=updated.exercises.find(row=>!row.completed);if(active.guidance_level==="full"&&following)void speak(`Done. Next is ${following.exercise.name}.`)}
  async function action(value:"pause"|"resume"|"submit"|"abandon"){const item=await updateWorkoutSessionState(active.id,value);setSessions(value==="submit"||value==="abandon"?[]:[item])}
  if(loading)return <View style={styles.center}><ActivityIndicator color="#2ad1a3"/></View>;
  if(active)return <ScrollView contentContainerStyle={styles.page}><Text style={styles.kicker}>IN PROGRESS</Text><Text style={styles.title}>{active.title}</Text><Text style={styles.muted}>{active.mode} · {active.guidance_level} guidance · {active.status}</Text>{next?<View style={styles.hero}><Text style={styles.next}>UP NEXT</Text><Text style={styles.exercise}>{next.exercise.name}</Text><Text style={styles.target}>{currentSet?targetText(currentSet.target):"Complete exercise"}</Text>{next.phase_type==="timed"&&<Text style={styles.timer}>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,"0")}</Text>}<View style={styles.actions}>{next.phase_type==="timed"&&currentSet?.status!=="active"&&<Button label="Start phase" primary onPress={startTimedSet}/>}<Button label="I did it" primary onPress={()=>completeSet(false)}/><Button label="Skip" onPress={()=>completeSet(true)}/></View><View style={styles.sets}>{next.set_logs.map(set=><View key={set.id} style={[styles.setChip,set.status==="completed"&&styles.setDone]}><Text style={styles.chipText}>{set.set_index}</Text></View>)}</View></View>:<View style={styles.hero}><Text style={styles.exercise}>Session complete</Text><Text style={styles.muted}>Build the report, edit anything that needs correcting, then submit.</Text><Button label={active.status==="draft"?"Submit report":"Review report"} primary onPress={async()=>{if(active.status==="draft")return action("submit");const item=await finishWorkoutSession(active.id,{draft:true});setSessions([item])}}/></View>}<View style={styles.footer}><Button label={active.status==="paused"?"Resume":"Pause"} onPress={()=>action(active.status==="paused"?"resume":"pause")}/><Button label="End early" onPress={async()=>{const item=await finishWorkoutSession(active.id,{draft:true});setSessions([item])}}/><Button label="Abandon" onPress={()=>action("abandon")}/></View></ScrollView>;
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.kicker}>TRAINING</Text><Text style={styles.title}>Choose today’s session</Text><Text style={styles.muted}>Checklist when you want freedom. Guided when you want Corv in your ear.</Text>{plans.flatMap(plan=>(plan.sessions?.length?plan.sessions:[{id:"",name:plan.title,exercises:plan.exercises} as any]).map(day=><View style={styles.card} key={`${plan.id}-${day.id}`}><Text style={styles.plan}>{day.name}</Text><Text style={styles.muted}>{plan.title} · {day.exercises.length} exercises</Text><View style={styles.actions}><Button label="Checklist" onPress={()=>start(plan,day.id,"checklist","minimal")}/><Button label="Minimal cues" onPress={()=>start(plan,day.id,"guided","minimal")}/><Button label="Full audio" primary onPress={()=>start(plan,day.id,"guided","full")}/></View></View>))}{!plans.length&&<Text style={styles.muted}>Create a workout plan on web or ask Corv to make one.</Text>}</ScrollView>
}
function Button({label,onPress,primary=false}:{label:string;onPress:()=>void|Promise<void>;primary?:boolean}){return <TouchableOpacity style={[styles.button,primary&&styles.primary]} onPress={()=>void onPress()}><Text style={[styles.buttonText,primary&&styles.primaryText]}>{label}</Text></TouchableOpacity>}
const styles=StyleSheet.create({center:{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:"#07111f"},page:{padding:18,paddingBottom:50,backgroundColor:"#07111f",minHeight:"100%"},kicker:{color:"#2ad1a3",fontSize:11,fontWeight:"800",letterSpacing:2},title:{color:"#f8fafc",fontSize:28,fontWeight:"800",marginTop:5},muted:{color:"#94a3b8",marginTop:5,lineHeight:20},card:{padding:16,borderRadius:16,borderWidth:1,borderColor:"#243247",backgroundColor:"#0d1828",marginTop:14},plan:{color:"#f8fafc",fontSize:19,fontWeight:"700"},actions:{flexDirection:"row",flexWrap:"wrap",gap:9,marginTop:14},button:{borderWidth:1,borderColor:"#334155",borderRadius:10,paddingHorizontal:14,paddingVertical:10},primary:{backgroundColor:"#2ad1a3",borderColor:"#2ad1a3"},buttonText:{color:"#e2e8f0",fontWeight:"700"},primaryText:{color:"#041316"},hero:{padding:20,borderRadius:20,borderWidth:1,borderColor:"#2b3b50",backgroundColor:"#0d1828",marginTop:22},next:{color:"#2ad1a3",fontSize:11,fontWeight:"800",letterSpacing:2},exercise:{color:"#fff",fontSize:30,fontWeight:"800",marginTop:6},target:{color:"#cbd5e1",fontSize:17,marginTop:8},timer:{color:"#f8fafc",fontSize:64,fontWeight:"300",fontVariant:["tabular-nums"],marginTop:14},sets:{flexDirection:"row",gap:8,marginTop:18},setChip:{width:34,height:34,borderRadius:17,borderWidth:1,borderColor:"#475569",alignItems:"center",justifyContent:"center"},setDone:{backgroundColor:"#166534",borderColor:"#2ad1a3"},chipText:{color:"#fff",fontWeight:"700"},footer:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:18}});
