# Generated by Django 5.2.3 on 2026-09-25 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_active_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexerciselog',
            name='block_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='workoutexerciselog',
            name='block_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='workoutexerciselog',
            name='cycle_index',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutexerciselog',
            name='phase_type',
            field=models.CharField(default='reps', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutexerciselog',
            name='set_targets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='block_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='block_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='cycle_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='phase_type',
            field=models.CharField(default='reps', max_length=20),
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='set_targets',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='accumulated_pause_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='guidance_level',
            field=models.CharField(default='minimal', max_length=24),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='mode',
            field=models.CharField(default='checklist', max_length=24),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('draft', 'Draft report'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='completed', max_length=16),
        ),
        migrations.CreateModel(
            name='WorkoutPlanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('guidance_mode', models.CharField(default='checklist', max_length=24)),
                ('auto_start_phases', models.BooleanField(default=False)),
                ('guidance_level', models.CharField(default='minimal', max_length=24)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_sessions', to='workout.workoutplan')),
            ],
            options={
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.AddField(
            model_name='workoutplanexercise',
            name='planned_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout.workoutplansession'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='planned_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_sessions', to='workout.workoutplansession'),
        ),
        migrations.CreateModel(
            name='WorkoutSetLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_index', models.PositiveIntegerField(default=1)),
                ('target', models.JSONField(blank=True, default=dict)),
                ('actual', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('exercise_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_logs', to='workout.workoutexerciselog')),
            ],
            options={
                'ordering': ['set_index'],
                'constraints': [models.UniqueConstraint(fields=('exercise_log', 'set_index'), name='workout_unique_exercise_set')],
            },
        ),
    ]
