# Generated by Django 5.2.3 on 2026-09-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_workoutexerciselog_block_key_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workoutplanexercise',
            name='workout_unique_plan_exercise_order',
        ),
        migrations.AddConstraint(
            model_name='workoutplanexercise',
            constraint=models.UniqueConstraint(condition=models.Q(('planned_session__isnull', False)), fields=('planned_session', 'order_index'), name='workout_unique_session_exercise_order'),
        ),
        migrations.AddConstraint(
            model_name='workoutplanexercise',
            constraint=models.UniqueConstraint(condition=models.Q(('planned_session__isnull', True)), fields=('plan', 'order_index'), name='workout_unique_plan_level_exercise_order'),
        ),
    ]
