import { createApi } from "../../shared/api";

const API_BASE = import.meta.env.VITE_API_BASE || "/api";

const api = createApi({
  baseUrl: API_BASE,
  getToken: () => localStorage.getItem("appAccessToken"),
});

export const {
  fetchChats,
  createChat,
  renameChat,
  deleteChat,
  fetchMessages,
  fetchJobMessages,
  fetchJobMessagesDirect,
  sendText,
  sendVoice,
  fetchJobs,
  fetchJob,
  cancelJob,
  fetchJobEvents,
  restartStudyJob,
  fetchUsageRecent,
  fetchUsageSummary,
  fetchSettings,
  updateSettings,
  fetchCalendarCombined,
  fetchObjectiveRoots,
  fetchObjectiveTree,
  fetchObjective,
  fetchObjectiveTasks,
  createObjective,
  updateObjective,
  deleteObjective,
  createObjectiveTask,
  updateObjectiveTask,
  deleteObjectiveTask,
  fetchObjectiveLogs,
  createObjectiveLog,
  updateObjectiveLog,
  deleteObjectiveLog,
  fetchStudyCourses,
  createStudyCourse,
  updateStudyCourse,
  deleteStudyCourse,
  fetchStudyTopics,
  fetchStudyExams,
  fetchStudyMaterials,
  createStudyTopic,
  createStudyExam,
  updateStudyExam,
  deleteStudyExam,
  updateStudyTopic,
  deleteStudyTopic,
  uploadStudyMaterial,
  fetchStudyAssignments,
  getStudyAssignment,
  getStudyAssignmentOriginalUrl,
  createStudyAssignment,
  updateStudyAssignmentStatus,
  deleteStudyAssignment,
  createSoftEvent,
  replanCalendar,
  createHardEventTaskLink,
  deleteHardEventTaskLink,
  fetchSoftEvent,
  updateSoftEvent,
  deleteSoftEvent,
  promoteSoftSlot,
  markSoftSlotOutcome,
  fetchScheduledTasks,
  createScheduledTask,
  updateScheduledTask,
  fetchScheduledTaskRuns,
  registerPushToken,
  fetchInboxMessages,
  markMessageRead,
  fetchCallSessions,
  createCallSession,
  updateCallSession,
  addCallTranscriptEntry,
  createRealtimeToken,
  fetchTopicAudiobookVersions,
  createTopicAudiobookVersion,
  previewTopicAudiobookVoice,
  getTopicAudiobookDownloadUrl,
} = api;
