import { useEffect, useMemo, useRef, useState } from "react";
import { deleteFile, fetchFiles, uploadFile } from "./api";
import type { ManagedFile } from "./types";
import FileCard from "./FileCard";

export default function FilesPanel() {
  const [files, setFiles] = useState<ManagedFile[]>([]); const [search, setSearch] = useState(""); const [tag, setTag] = useState(""); const [kind, setKind] = useState("all");
  const [loading, setLoading] = useState(true); const [uploading, setUploading] = useState(false); const [error, setError] = useState(""); const picker = useRef<HTMLInputElement | null>(null);
  async function refresh() { setLoading(true); setError(""); try { setFiles((await fetchFiles()).files); } catch (err: any) { setError(err.message || "Could not load files"); } finally { setLoading(false); } }
  useEffect(() => { refresh(); }, []);
  const tags = useMemo(() => [...new Set(files.flatMap((file) => file.tags))].sort(), [files]);
  const visible = useMemo(() => files.filter((file) => { const needle = search.trim().toLowerCase(); const matchesSearch = !needle || file.filename.toLowerCase().includes(needle) || file.tags.some((value) => value.toLowerCase().includes(needle)) || JSON.stringify(file.metadata).toLowerCase().includes(needle); const matchesTag = !tag || file.tags.includes(tag); const matchesKind = kind === "all" || (kind === "image" ? file.content_type.startsWith("image/") : kind === "document" ? file.content_type.startsWith("text/") || file.content_type.includes("pdf") || file.content_type.includes("document") : file.content_type.startsWith("audio/") || file.content_type.startsWith("video/")); return matchesSearch && matchesTag && matchesKind; }), [files, search, tag, kind]);
  async function addFiles(selected: FileList | null) { if (!selected?.length) return; setUploading(true); setError(""); try { for (const file of Array.from(selected)) await uploadFile(file); await refresh(); } catch (err: any) { setError(err.message || "Upload failed"); } finally { setUploading(false); if (picker.current) picker.current.value = ""; } }
  async function remove(file: ManagedFile) { if (!window.confirm(`Delete ${file.filename}?`)) return; try { await deleteFile(file.id); setFiles((items) => items.filter((item) => item.id !== file.id)); } catch (err: any) { setError(err.message || "Delete failed"); } }
  return <div className="settings-panel files-panel"><header className="main-header"><div><p className="eyebrow">Library</p><h2>Files</h2><p className="muted small">Preview, download, and manage files created by Corv and coding sessions.</p></div><div className="main-actions"><input ref={picker} hidden type="file" multiple onChange={(event) => addFiles(event.target.files)} /><button className="primary" type="button" disabled={uploading} onClick={() => picker.current?.click()}>{uploading ? "Uploading…" : "Upload files"}</button><button className="ghost" type="button" disabled={loading} onClick={refresh}>Refresh</button></div></header>{error && <div className="alert">{error}</div>}<div className="file-toolbar card"><label className="field file-search"><span>Search</span><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Filename, tag, or metadata" /></label><label className="field"><span>Tag</span><select value={tag} onChange={(event) => setTag(event.target.value)}><option value="">All tags</option>{tags.map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label className="field"><span>Type</span><select value={kind} onChange={(event) => setKind(event.target.value)}><option value="all">All types</option><option value="image">Images</option><option value="document">Documents</option><option value="media">Audio & video</option></select></label></div><div className="file-results-head"><span>{visible.length} of {files.length} files</span>{(search || tag || kind !== "all") && <button type="button" className="ghost pill-action" onClick={() => { setSearch(""); setTag(""); setKind("all"); }}>Clear filters</button>}</div>{loading ? <p className="muted">Loading files…</p> : visible.length ? <div className="managed-file-grid">{visible.map((file) => <FileCard key={file.id} file={file} onDelete={remove} />)}</div> : <div className="card file-empty"><h3>{files.length ? "No matching files" : "No files yet"}</h3><p className="muted">{files.length ? "Try changing your search or filters." : "Upload a file or ask a coding session to create one."}</p></div>}</div>;
}
