import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import type { KnowledgeEntity, KnowledgeEntityType, KnowledgeSearchResult, LocationSearchResult, UserNote } from "../../shared/types";
import { createKnowledgeEntity, createNote, deleteKnowledgeEntity, deleteNote, fetchKnowledgeEntities, fetchKnowledgeTags, fetchNotes, searchKnowledge, searchLocations, updateKnowledgeEntity, updateNote } from "./api";
import LocationMapPicker from "./LocationMapPicker";
import "./notes.css";

type NoteType="note"|KnowledgeEntityType;
type Draft={type:NoteType;content:string;name:string;description:string;tags:string;latitude:string;longitude:string;relationship:string;facts:string;expiresAt:string};
type BrowseItem=(UserNote&{knowledge_type:"note"})|KnowledgeEntity;
const EMPTY:Draft={type:"note",content:"",name:"",description:"",tags:"",latitude:"",longitude:"",relationship:"",facts:"",expiresAt:""};
const toLocalDateTime=(value?:string|null)=>{if(!value)return "";const date=new Date(value);if(Number.isNaN(date.getTime()))return "";const local=new Date(date.getTime()-date.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)};
const parseTags=(value:string)=>Array.from(new Set(value.split(",").map(x=>x.trim()).filter(Boolean)));
const parseFacts=(value:string)=>value.split("\n").map(x=>x.trim()).filter(Boolean);
const errorText=(error:unknown)=>error instanceof Error?error.message:"Something went sideways.";
const labelFor=(type:NoteType)=>type==="note"?"Generic":type==="person"?"Person":"Location";

export default function NotesPanel(){
  const [notes,setNotes]=useState<UserNote[]>([]),[locations,setLocations]=useState<KnowledgeEntity[]>([]),[people,setPeople]=useState<KnowledgeEntity[]>([]),[tags,setTags]=useState<string[]>([]);
  const [draft,setDraft]=useState<Draft>(EMPTY),[editingId,setEditingId]=useState<string|null>(null),[filterType,setFilterType]=useState<"all"|NoteType>("all"),[selectedTags,setSelectedTags]=useState<string[]>([]);
  const [query,setQuery]=useState(""),[searchResults,setSearchResults]=useState<KnowledgeSearchResult[]|null>(null),[preferred,setPreferred]=useState<string[]>([]);
  const [placeQuery,setPlaceQuery]=useState(""),[placeResults,setPlaceResults]=useState<LocationSearchResult[]>([]),[placeSearching,setPlaceSearching]=useState(false);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [n,l,p,t]=await Promise.all([fetchNotes(),fetchKnowledgeEntities("location"),fetchKnowledgeEntities("person"),fetchKnowledgeTags()]);setNotes(n.notes);setLocations(l.entities);setPeople(p.entities);setTags(t.tags);setSelectedTags(current=>current.filter(selected=>t.tags.includes(selected)))}catch(err){setError(errorText(err))}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const browse=useMemo<BrowseItem[]>(()=>{const base:BrowseItem[]=searchResults?(searchResults as BrowseItem[]):[...notes.map(note=>({...note,knowledge_type:"note" as const})),...locations,...people];return base.filter(item=>(filterType==="all"||item.knowledge_type===filterType)&&selectedTags.every(tag=>item.tags.includes(tag)))},[searchResults,notes,locations,people,filterType,selectedTags]);
  function reset(type:NoteType=draft.type){setDraft({...EMPTY,type});setEditingId(null)}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError("");try{const common={tags:parseTags(draft.tags)};if(draft.type==="note"){if(!draft.content.trim())throw new Error("Give the note something to remember.");const payload={content:draft.content.trim(),expires_at:draft.expiresAt?new Date(draft.expiresAt).toISOString():null,...common};if(editingId)await updateNote(editingId,payload);else await createNote(payload)}else{const shared={name:draft.name.trim(),description:draft.description.trim(),...common};const payload=draft.type==="location"?{...shared,latitude:Number(draft.latitude),longitude:Number(draft.longitude)}:{...shared,relationship:draft.relationship.trim(),facts:parseFacts(draft.facts)};if(editingId)await updateKnowledgeEntity(draft.type,editingId,payload);else await createKnowledgeEntity(draft.type,payload)}reset(draft.type);setSearchResults(null);setQuery("");await load()}catch(err){setError(errorText(err))}finally{setSaving(false)}}
  function edit(item:BrowseItem){setEditingId(item.id);if(item.knowledge_type==="note")setDraft({...EMPTY,type:"note",content:item.content,tags:item.tags.join(", "),expiresAt:toLocalDateTime(item.expires_at)});else setDraft({...EMPTY,type:item.knowledge_type,name:item.name,description:item.description,tags:item.tags.join(", "),latitude:String(item.data.latitude??""),longitude:String(item.data.longitude??""),relationship:String(item.data.relationship??""),facts:(item.data.facts||[]).join("\n")});window.scrollTo({top:0,behavior:"smooth"})}
  async function remove(item:BrowseItem){if(!window.confirm(`Delete this ${labelFor(item.knowledge_type).toLowerCase()} note? Corv will stop recalling it.`))return;try{if(item.knowledge_type==="note")await deleteNote(item.id);else await deleteKnowledgeEntity(item.knowledge_type,item.id);if(editingId===item.id)reset(item.knowledge_type);setSearchResults(null);await load()}catch(err){setError(errorText(err))}}
  async function findPlace(){const clean=placeQuery.trim();if(!clean)return;setPlaceSearching(true);setError("");try{const result=await searchLocations(clean);setPlaceResults(result.results)}catch(err){setError(errorText(err))}finally{setPlaceSearching(false)}}
  function choosePlace(place:LocationSearchResult){setDraft(current=>({...current,name:current.name||place.name,latitude:String(place.latitude),longitude:String(place.longitude),description:current.description||place.display_name}));setPlaceResults([])}
  async function search(event:FormEvent){event.preventDefault();const clean=query.trim();if(!clean){setSearchResults(null);setPreferred([]);return}setLoading(true);try{const result=await searchKnowledge(clean,selectedTags,100);setSearchResults(result.results);setPreferred(result.preferred_types)}catch(err){setError(errorText(err))}finally{setLoading(false)}}
  function setType(type:NoteType){reset(type)}
  async function toggleTag(tag:string){
    const next=selectedTags.includes(tag)?selectedTags.filter(value=>value!==tag):[...selectedTags,tag];
    setSelectedTags(next);
    if(searchResults===null||!query.trim())return;
    setLoading(true);setError("");
    try{const result=await searchKnowledge(query.trim(),next,100);setSearchResults(result.results);setPreferred(result.preferred_types)}catch(err){setError(errorText(err))}finally{setLoading(false)}
  }
  function clearTags(){setSelectedTags([]);if(searchResults!==null&&query.trim()){setLoading(true);setError("");void searchKnowledge(query.trim(),[],100).then(result=>{setSearchResults(result.results);setPreferred(result.preferred_types)}).catch(err=>setError(errorText(err))).finally(()=>setLoading(false))}}
  return <section className="notes-panel unified-notes"><header className="main-header notes-header"><div><p className="eyebrow">Memory</p><h2>Notes</h2><p className="muted">Generic, people, and places. One filing cabinet; smarter drawers.</p></div><button className="ghost" onClick={()=>void load()} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button></header>{error&&<div className="alert" role="alert">{error}</div>}
    <div className="unified-notes-layout"><form className="card unified-note-editor" onSubmit={submit}><div className="card-head"><div><p className="eyebrow">{editingId?"Edit":"Add"}</p><h3>{labelFor(draft.type)} note</h3></div>{editingId&&<button className="ghost pill-action" type="button" onClick={()=>reset()}>Cancel</button>}</div><label className="field"><span>Type</span><select value={draft.type} disabled={Boolean(editingId)} onChange={e=>setType(e.target.value as NoteType)}><option value="note">Generic</option><option value="location">Location</option><option value="person">Person</option></select></label>
      {draft.type==="note"?<label className="field"><span>Note</span><textarea required rows={7} value={draft.content} onChange={e=>setDraft({...draft,content:e.target.value})} placeholder="A preference, useful fact, or anything else…"/></label>:<><label className="field"><span>Name</span><input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>{draft.type==="location"?<><div className="location-picker"><div><label className="field"><span>Find on map</span><div><input value={placeQuery} onChange={e=>setPlaceQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void findPlace()}}} placeholder="Address, venue, or place name"/><button className="ghost" type="button" onClick={()=>void findPlace()} disabled={placeSearching}>{placeSearching?"Searching…":"Find"}</button></div></label></div>{placeResults.length>0&&<div className="location-search-results">{placeResults.map((place,index)=><button type="button" key={`${place.latitude}-${place.longitude}-${index}`} onClick={()=>choosePlace(place)}><strong>{place.name}</strong><span>{place.display_name}</span></button>)}</div>}<LocationMapPicker latitude={draft.latitude!==""?Number(draft.latitude):undefined} longitude={draft.longitude!==""?Number(draft.longitude):undefined} onPick={(latitude,longitude)=>setDraft(current=>({...current,latitude:String(latitude),longitude:String(longitude)}))}/><small>Search powered by <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap contributors</a>. Searches are sent to the geocoding provider; avoid private information.</small></div><div className="knowledge-coordinate-fields"><label className="field"><span>Latitude</span><input required type="number" min="-90" max="90" step="any" value={draft.latitude} onChange={e=>setDraft({...draft,latitude:e.target.value})}/></label><label className="field"><span>Longitude</span><input required type="number" min="-180" max="180" step="any" value={draft.longitude} onChange={e=>setDraft({...draft,longitude:e.target.value})}/></label></div></>:<><label className="field"><span>Relationship</span><input value={draft.relationship} onChange={e=>setDraft({...draft,relationship:e.target.value})} placeholder="friend, colleague, family…"/></label><label className="field"><span>Facts</span><textarea rows={4} value={draft.facts} onChange={e=>setDraft({...draft,facts:e.target.value})} placeholder="One fact per line"/></label></>}<label className="field"><span>Description</span><textarea rows={3} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label></>}
      {draft.type==="note"&&<label className="field"><span>Expires (optional)</span><input type="datetime-local" value={draft.expiresAt} onChange={e=>setDraft({...draft,expiresAt:e.target.value})}/><small>Leave blank for a permanent note. Timed notes stop being recalled after this date and are then safely cleaned up.</small></label>}
      <label className="field"><span>Tags</span><input value={draft.tags} onChange={e=>setDraft({...draft,tags:e.target.value})} placeholder="personal, travel, work"/></label><button className="primary" disabled={saving}>{saving?"Saving…":editingId?"Save changes":"Add note"}</button></form>
      <div className="unified-notes-browser"><form className="card unified-note-search" onSubmit={search}><div><p className="eyebrow">Search</p><h3>All notes</h3></div><div className="knowledge-search-row"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search generic notes, people, and locations"/><button className="primary">Search</button>{searchResults&&<button type="button" className="ghost" onClick={()=>{setQuery("");setSearchResults(null);setPreferred([])}}>Clear</button>}</div>{searchResults&&<p className="muted small">{preferred.length?`${preferred.map(x=>labelFor(x as NoteType)).join(", ")} notes checked first, then everything else.`:"Semantic results across every note type."}</p>}</form>
        <div className="unified-note-filters"><div className="unified-type-tabs">{(["all","note","location","person"] as const).map(type=><button type="button" className={filterType===type?"active":""} key={type} onClick={()=>setFilterType(type)}>{type==="all"?"All":labelFor(type)}</button>)}</div><div className="tag-filter-head"><span>Tags{selectedTags.length?` · ${selectedTags.length} selected`:""}</span>{selectedTags.length>0&&<button type="button" className="ghost clear-tag-filters" onClick={clearTags}>Clear tags</button>}</div><div className="notes-tag-list filter-list" aria-label="Filter notes by tag">{tags.map(tag=>{const active=selectedTags.includes(tag);return <button type="button" aria-pressed={active} className={`note-tag filter ${active?"active":""}`} key={tag} onClick={()=>void toggleTag(tag)}><span className="tag-selected-mark" aria-hidden="true">✓</span>#{tag}</button>})}{!tags.length&&<span className="muted small">No tags yet.</span>}</div></div>
        <div className="notes-results-head"><span>{searchResults?`Results for “${query}”`:"All notes"}</span><strong>{browse.length}</strong></div><div className="unified-note-grid">{browse.map(item=><article className="card unified-note-card" key={`${item.knowledge_type}-${item.id}`}><header><span className={`note-type ${item.knowledge_type}`}>{labelFor(item.knowledge_type)}</span>{item.knowledge_type==="location"&&<small>{Number(item.data.latitude).toFixed(4)}, {Number(item.data.longitude).toFixed(4)}</small>}</header>{item.knowledge_type==="note"?<p>{item.content}</p>:<><h4>{item.name}</h4>{item.knowledge_type==="person"&&item.data.relationship&&<strong className="knowledge-relationship">{String(item.data.relationship)}</strong>}<p>{item.description||"No description"}</p>{item.knowledge_type==="person"&&Boolean(item.data.facts?.length)&&<ul>{item.data.facts!.map((fact,index)=><li key={index}>{fact}</li>)}</ul>}</>}{item.knowledge_type==="note"&&item.expires_at&&<div className="note-expiry"><span>Timed</span><time dateTime={item.expires_at}>Expires {new Date(item.expires_at).toLocaleString()}</time></div>}<div className="notes-tag-list">{item.tags.map(tag=><span className="note-tag" key={tag}>#{tag}</span>)}</div><footer><span className="muted small">{item.source||"No source"}</span><div className="note-actions"><button className="ghost pill-action" onClick={()=>edit(item)}>Edit</button><button className="ghost pill-action danger" onClick={()=>void remove(item)}>Delete</button></div></footer></article>)}</div>{!loading&&!browse.length&&<div className="notes-empty"><strong>No notes found.</strong><span className="muted">Try another search or type.</span></div>}</div></div>
  </section>
}
