import { FormEvent, useEffect, useMemo, useState } from "react";
import { createWorkoutExercise, createWorkoutGoal, createWorkoutPlan, deleteWorkoutExercise, deleteWorkoutPlan, createWorkoutSession, deleteWorkoutSession, fetchActiveWorkoutSessions, finishWorkoutSession, startWorkoutSession, updateWorkoutSessionItem, fetchWorkoutDashboard, fetchWorkoutExercises, fetchWorkoutGoals, fetchWorkoutPlans, fetchWorkoutSessions, updateWorkoutGoal } from "./api";
import type { WorkoutDashboard, WorkoutExercise, WorkoutExerciseSpec, WorkoutGoal, WorkoutPlan, WorkoutSession } from "./types";
import "./workout.css";

const emptyLog=():WorkoutExerciseSpec=>({name:"",sets:3,reps:10});
function errText(error:unknown){if(!(error instanceof Error))return "Something went wrong";try{const body=JSON.parse(error.message);return body.detail||body.message||error.message}catch{return error.message}}
function localInput(date=new Date()){const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16)}
function durationText(seconds:number){if(!seconds)return "—";const mins=Math.round(seconds/60);return mins<60?`${mins} min`:`${Math.floor(mins/60)}h ${mins%60}m`}
function LineChart({points,label,color="#2ad1a3"}:{points:number[];label:string;color?:string}){const width=680,height=180,pad=18,max=Math.max(...points,1),step=points.length>1?(width-pad*2)/(points.length-1):0;const path=points.map((value,index)=>`${index?"L":"M"} ${pad+index*step} ${height-pad-(value/max)*(height-pad*2)}`).join(" ");return <div className="workout-chart"><div><strong>{label}</strong><span>Peak {Math.round(max*10)/10}</span></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={label}><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad}/><path d={path} style={{stroke:color}}/>{points.map((value,index)=><circle key={index} cx={pad+index*step} cy={height-pad-(value/max)*(height-pad*2)} r="3" style={{fill:color}}><title>{value}</title></circle>)}</svg></div>}

export default function WorkoutPanel(){
  const [dashboard,setDashboard]=useState<WorkoutDashboard|null>(null),[plans,setPlans]=useState<WorkoutPlan[]>([]),[sessions,setSessions]=useState<WorkoutSession[]>([]),[activeSessions,setActiveSessions]=useState<WorkoutSession[]>([]),[exercises,setExercises]=useState<WorkoutExercise[]>([]),[goals,setGoals]=useState<WorkoutGoal[]>([]);
  const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [logTitle,setLogTitle]=useState("Workout"),[logPlan,setLogPlan]=useState(""),[logStarted,setLogStarted]=useState(localInput()),[logEnded,setLogEnded]=useState(""),[logNotes,setLogNotes]=useState(""),[logRows,setLogRows]=useState<WorkoutExerciseSpec[]>([emptyLog()]);
  const [planTitle,setPlanTitle]=useState(""),[planGoal,setPlanGoal]=useState(""),[planDescription,setPlanDescription]=useState(""),[planText,setPlanText]=useState("");
  const [exerciseName,setExerciseName]=useState(""),[exerciseGroup,setExerciseGroup]=useState(""),[exerciseEquipment,setExerciseEquipment]=useState("");
  const [goalTitle,setGoalTitle]=useState("Train consistently"),[goalMetric,setGoalMetric]=useState("sessions_per_week"),[goalTarget,setGoalTarget]=useState("3"),[goalExercise,setGoalExercise]=useState("");
  const [trendExercise,setTrendExercise]=useState("");
  async function refresh(){setLoading(true);try{const [d,p,s,a,e,g]=await Promise.all([fetchWorkoutDashboard(90,trendExercise),fetchWorkoutPlans(),fetchWorkoutSessions({limit:100}),fetchActiveWorkoutSessions(),fetchWorkoutExercises(),fetchWorkoutGoals()]);setDashboard(d);setPlans(p.plans);setSessions(s.sessions);setActiveSessions(a.sessions);setExercises(e.exercises);setGoals(g.goals);setError("")}catch(err){setError(errText(err))}finally{setLoading(false)}}
  useEffect(()=>{void refresh()},[]);
  useEffect(()=>{if(!dashboard)return;fetchWorkoutDashboard(90,trendExercise).then(setDashboard).catch(()=>undefined)},[trendExercise]);
  const weeklyGoal=useMemo(()=>goals.find(goal=>goal.active&&goal.metric==="sessions_per_week"),[goals]);
  function updateRow(index:number,field:keyof WorkoutExerciseSpec,value:string){setLogRows(rows=>rows.map((row,i)=>i===index?{...row,[field]:["sets","reps","weight_kg","duration_seconds","distance_km","rpe"].includes(field)?(value===""?undefined:Number(value)):value}:row))}
  async function submitLog(event:FormEvent){event.preventDefault();const rows=logRows.filter(row=>row.name.trim());if(!rows.length){setError("Add at least one exercise");return}setSaving(true);try{const item=await createWorkoutSession({title:logTitle,plan:logPlan||undefined,started_at:new Date(logStarted).toISOString(),ended_at:logEnded?new Date(logEnded).toISOString():undefined,notes:logNotes,exercises:rows});setNotice(`Logged ${item.exercises.length} exercise${item.exercises.length===1?"":"s"}${item.created_exercises?.length?` · added ${item.created_exercises.join(", ")} to the directory`:""}.`);setLogRows([emptyLog()]);setLogNotes("");setLogEnded("");setLogStarted(localInput());await refresh()}catch(err){setError(errText(err))}finally{setSaving(false)}}
  function parsePlanExercises():WorkoutExerciseSpec[]{const text=planText.trim();if(!text)return[];if(text.startsWith("[")){const value=JSON.parse(text);if(!Array.isArray(value))throw new Error("Imported plan JSON must be an array");return value}return text.split("\n").map(line=>line.trim()).filter(Boolean).map(line=>{const [name,sets,reps,weight]=line.split("|").map(x=>x.trim());return{name,sets:sets?Number(sets):undefined,reps:reps||undefined,weight_kg:weight?Number(weight):undefined}})}
  async function startPlanSession(planId:string){setSaving(true);try{await startWorkoutSession({plan:planId});setNotice("Workout started. Time to make the checklist regret existing.");await refresh()}catch(err){setError(errText(err))}finally{setSaving(false)}}
  async function startAdHocSession(){const rows=logRows.filter(row=>row.name.trim());if(!rows.length){setError("Add at least one exercise first");return}setSaving(true);try{await startWorkoutSession({title:logTitle,started_at:new Date(logStarted).toISOString(),notes:logNotes,exercises:rows});setNotice("Live workout started.");await refresh()}catch(err){setError(errText(err))}finally{setSaving(false)}}
  async function toggleActiveItem(sessionId:string,logId:string,completed:boolean){try{const item=await updateWorkoutSessionItem(logId,{completed});setActiveSessions(items=>items.map(session=>session.id===sessionId?{...session,exercises:session.exercises.map(row=>row.id===logId?item:row)}:session))}catch(err){setError(errText(err))}}
  async function finishActiveSession(sessionId:string){setSaving(true);try{await finishWorkoutSession(sessionId);setNotice("Workout finished and moved to history.");await refresh()}catch(err){setError(errText(err))}finally{setSaving(false)}}
  async function removeSession(session:WorkoutSession){
    if(!window.confirm(`Delete ${session.title||"this workout"} from ${new Date(session.started_at).toLocaleString()}?`))return;
    setSaving(true);setError("");
    try{await deleteWorkoutSession(session.id);setNotice("Workout session deleted.");await refresh()}catch(err){setError(errText(err))}finally{setSaving(false)}
  }
  async function submitPlan(event:FormEvent){event.preventDefault();setSaving(true);try{const rows=parsePlanExercises();await createWorkoutPlan({title:planTitle,goal:planGoal,description:planDescription,source:"import",exercises:rows});setPlanTitle("");setPlanGoal("");setPlanDescription("");setPlanText("");setNotice("Workout plan saved. No clipboard archaeology required next time.");await refresh()}catch(err){setError(errText(err))}finally{setSaving(false)}}
  async function submitExercise(event:FormEvent){event.preventDefault();setSaving(true);try{const item=await createWorkoutExercise({name:exerciseName,muscle_group:exerciseGroup,equipment:exerciseEquipment});setNotice(item.created?`${item.name} joined the exercise directory.`:`${item.name} was already in the directory.`);setExerciseName("");setExerciseGroup("");setExerciseEquipment("");await refresh()}catch(err){setError(errText(err))}finally{setSaving(false)}}
  async function removePlan(plan:WorkoutPlan){if(!window.confirm(`Delete the plan “${plan.title}”? Historical sessions will remain.`))return;setSaving(true);try{const result=await deleteWorkoutPlan(plan.id);setNotice(`Plan deleted${result.preserved_sessions?` · ${result.preserved_sessions} historical session${result.preserved_sessions===1?"":"s"} preserved`:""}.`);await refresh()}catch(err){setError(errText(err))}finally{setSaving(false)}}
  async function removeExercise(exercise:WorkoutExercise){if(!window.confirm(`Delete “${exercise.name}” from the exercise directory? If it is referenced, you will be asked to remove those references separately through Corv.`))return;setSaving(true);try{await deleteWorkoutExercise(exercise.id);setNotice("Exercise deleted from the directory.");await refresh()}catch(err){setError(errText(err))}finally{setSaving(false)}}
  async function submitGoal(event:FormEvent){event.preventDefault();setSaving(true);try{await createWorkoutGoal({title:goalTitle,metric:goalMetric,target_value:Number(goalTarget),exercise:goalMetric==="exercise_weight_kg"?goalExercise:undefined,unit:goalMetric==="exercise_weight_kg"?"kg":goalMetric==="minutes_per_week"?"minutes":"sessions"});setNotice("Goal saved. Now comes the suspiciously physical part.");await refresh()}catch(err){setError(errText(err))}finally{setSaving(false)}}
  return <div className="settings-panel workout-panel">
    <header className="main-header"><div><p className="eyebrow">Training</p><h2>Workout</h2><p className="muted">Plans, logs, progress, and enough accountability to be useful.</p></div><button type="button" className="ghost" onClick={()=>void refresh()} disabled={loading}>Refresh</button></header>
    {error&&<div className="alert">{error}<button type="button" className="ghost pill-action" onClick={()=>setError("")}>Dismiss</button></div>}{notice&&<div className="workout-notice">{notice}<button type="button" onClick={()=>setNotice("")}>×</button></div>}
    <section className="card workout-active"><div className="card-head"><div><p className="eyebrow">Today</p><h3>Active workout</h3></div>{!activeSessions.length&&<select aria-label="Start saved workout plan" defaultValue="" onChange={e=>{if(e.target.value)void startPlanSession(e.target.value);e.target.value=""}} disabled={saving}><option value="">Start saved plan…</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.title}</option>)}</select>}</div>{activeSessions.length?activeSessions.map(session=><article className="workout-active-session" key={session.id}><header><div><strong>{session.title}</strong><span>Started {new Date(session.started_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div><b>{session.exercises.filter(row=>row.completed).length} / {session.exercises.length}</b></header><div>{session.exercises.map(row=><label className={row.completed?"done":""} key={row.id}><input type="checkbox" checked={row.completed} onChange={e=>void toggleActiveItem(session.id,row.id,e.target.checked)}/><span><strong>{row.exercise.name}</strong><small>{[row.sets&&`${row.sets} sets`,row.metadata?.prescribed_reps&&`${String(row.metadata.prescribed_reps)} reps`,row.reps&&`${row.reps} reps`,row.weight_kg&&`${row.weight_kg} kg`,row.duration_seconds&&`${row.duration_seconds}s`].filter(Boolean).join(" · ")||"Complete as planned"}</small></span></label>)}</div><button type="button" className="primary" disabled={saving} onClick={()=>void finishActiveSession(session.id)}>Finish workout</button></article>):<p className="muted">Nothing in progress. Start a saved plan, or build exercises below and choose “Start live session”.</p>}</section>
    <div className="workout-stat-grid"><article><small>Last 90 days</small><strong>{dashboard?.session_count||0}</strong><span>sessions</span></article><article><small>This week</small><strong>{dashboard?.current_week_sessions||0}{weeklyGoal?` / ${weeklyGoal.target_value}`:""}</strong><span>sessions</span></article><article><small>Current streak</small><strong>{dashboard?.current_streak_days||0}</strong><span>training days</span></article><article><small>Exercise directory</small><strong>{exercises.length}</strong><span>movements</span></article></div>
    <section className="workout-dashboard-grid">
      <div className="card workout-trends"><div className="card-head"><div><p className="eyebrow">Consistency</p><h3>Training trend</h3></div><select aria-label="Exercise trend" value={trendExercise} onChange={e=>setTrendExercise(e.target.value)}><option value="">All exercises</option>{exercises.map(x=><option key={x.id}>{x.name}</option>)}</select></div><LineChart label="Weekly sessions" points={(dashboard?.weekly||[]).map(x=>x.sessions)}/><LineChart label={trendExercise?`${trendExercise} volume (kg)`:"Daily training volume (kg)"} color="#60a5fa" points={trendExercise?(dashboard?.exercise_trend||[]).map(x=>x.volume_kg):(dashboard?.daily||[]).slice(-30).map(x=>x.volume_kg)}/></div>
      <div className="card workout-goals"><div className="card-head"><div><p className="eyebrow">Targets</p><h3>Active goals</h3></div></div>{dashboard?.goals.length?dashboard.goals.map(goal=><article key={goal.id}><div><strong>{goal.title}</strong><span>{goal.current_value} / {goal.target_value} {goal.unit}</span></div><div className="workout-progress"><i style={{width:`${goal.progress_percent}%`}}/></div><button type="button" className="ghost pill-action" onClick={()=>updateWorkoutGoal(goal.id,false).then(refresh)}>Archive</button></article>):<p className="muted">No goals yet. Ambition remains safely theoretical.</p>}
        <form onSubmit={submitGoal} className="workout-compact-form"><input required value={goalTitle} onChange={e=>setGoalTitle(e.target.value)} placeholder="Goal name"/><select value={goalMetric} onChange={e=>setGoalMetric(e.target.value)}><option value="sessions_per_week">Sessions / week</option><option value="minutes_per_week">Minutes / week</option><option value="exercise_weight_kg">Exercise weight</option></select><input required type="number" min="0.1" step="0.1" value={goalTarget} onChange={e=>setGoalTarget(e.target.value)} placeholder="Target"/>{goalMetric==="exercise_weight_kg"&&<input required list="exercise-options" value={goalExercise} onChange={e=>setGoalExercise(e.target.value)} placeholder="Exercise"/>}<button className="primary" disabled={saving}>Set goal</button></form>
      </div>
    </section>
    <section className="workout-main-grid">
      <form className="card workout-log-form" onSubmit={submitLog}><div className="card-head"><div><p className="eyebrow">Session logging</p><h3>Log workout</h3></div><button type="button" className="ghost" onClick={()=>setLogRows(rows=>[...rows,emptyLog()])}>Add exercise</button></div><div className="workout-form-grid"><label>Title<input required value={logTitle} onChange={e=>setLogTitle(e.target.value)}/></label><label>Plan<select value={logPlan} onChange={e=>setLogPlan(e.target.value)}><option value="">No plan</option>{plans.map(x=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label><label>Started<input required type="datetime-local" value={logStarted} onChange={e=>setLogStarted(e.target.value)}/></label><label>Ended (optional)<input type="datetime-local" value={logEnded} onChange={e=>setLogEnded(e.target.value)}/></label></div><datalist id="exercise-options">{exercises.map(x=><option key={x.id} value={x.name}/>)}</datalist><div className="workout-log-rows">{logRows.map((row,index)=><div className="workout-log-row" key={index}><input required list="exercise-options" value={row.name} onChange={e=>updateRow(index,"name",e.target.value)} placeholder="Exercise"/><input type="number" min="1" value={row.sets??""} onChange={e=>updateRow(index,"sets",e.target.value)} placeholder="Sets"/><input type="number" min="0" value={row.reps??""} onChange={e=>updateRow(index,"reps",e.target.value)} placeholder="Reps"/><input type="number" min="0" step="0.1" value={row.weight_kg??""} onChange={e=>updateRow(index,"weight_kg",e.target.value)} placeholder="kg"/><input type="number" min="0" value={row.duration_seconds??""} onChange={e=>updateRow(index,"duration_seconds",e.target.value)} placeholder="Seconds"/><input type="number" min="0" step="0.1" value={row.rpe??""} onChange={e=>updateRow(index,"rpe",e.target.value)} placeholder="RPE"/><button type="button" className="ghost" onClick={()=>setLogRows(rows=>rows.filter((_,i)=>i!==index))}>×</button></div>)}</div><label>Notes<textarea rows={3} value={logNotes} onChange={e=>setLogNotes(e.target.value)} placeholder="How it felt, substitutions, minor acts of heroism…"/></label><div className="workout-form-actions"><button className="primary" disabled={saving}>{saving?"Saving…":"Log completed workout"}</button><button type="button" className="ghost" disabled={saving} onClick={()=>void startAdHocSession()}>Start live session</button></div></form>
      <form className="card workout-plan-form" onSubmit={submitPlan}><div className="card-head"><div><p className="eyebrow">Plan builder</p><h3>Create or import plan</h3></div></div><label>Plan name<input required value={planTitle} onChange={e=>setPlanTitle(e.target.value)} placeholder="Three-day strength"/></label><label>Goal<input value={planGoal} onChange={e=>setPlanGoal(e.target.value)} placeholder="Build strength, run 5K…"/></label><label>Description<textarea rows={2} value={planDescription} onChange={e=>setPlanDescription(e.target.value)}/></label><label>Exercises<textarea required rows={8} value={planText} onChange={e=>setPlanText(e.target.value)} placeholder={"One per line: Exercise | sets | reps | kg\nSquat | 5 | 5 | 80\n\nOr paste a JSON array from an existing plan."}/></label><button className="primary" disabled={saving}>Save plan</button></form>
    </section>
    <section className="workout-library-grid"><div className="card"><div className="card-head"><div><p className="eyebrow">History</p><h3>Recent sessions</h3></div></div><div className="workout-history">{sessions.length?sessions.slice(0,20).map(session=><article key={session.id}><time>{new Date(session.started_at).toLocaleString()}</time><div><strong>{session.title||"Workout"}</strong><span>{session.exercises.map(x=>x.exercise.name).join(" · ")}</span></div><b>{durationText(session.duration_seconds)}</b><button type="button" className="ghost pill-action" disabled={saving} onClick={()=>void removeSession(session)}>Delete</button></article>):<p className="muted">No workouts logged yet.</p>}</div></div><div className="card"><div className="card-head"><div><p className="eyebrow">Directory</p><h3>Exercises</h3></div><span className="muted">{exercises.length}</span></div><form className="workout-directory-form" onSubmit={submitExercise}><input required value={exerciseName} onChange={e=>setExerciseName(e.target.value)} placeholder="Exercise name"/><input value={exerciseGroup} onChange={e=>setExerciseGroup(e.target.value)} placeholder="Muscle group"/><input value={exerciseEquipment} onChange={e=>setExerciseEquipment(e.target.value)} placeholder="Equipment"/><button className="primary" disabled={saving}>Add</button></form><div className="workout-exercise-list">{exercises.map(x=><article key={x.id}><div><strong>{x.name}</strong><span>{[x.muscle_group,x.equipment].filter(Boolean).join(" · ")||"Uncategorised"}</span></div><button type="button" className="ghost pill-action" disabled={saving} onClick={()=>void removeExercise(x)}>Delete</button></article>)}</div></div></section>
    <section className="card workout-plans"><div className="card-head"><div><p className="eyebrow">Saved programming</p><h3>Workout plans</h3></div></div><div>{plans.length?plans.map(plan=><article key={plan.id}><header><div><strong>{plan.title}</strong><span>{plan.goal||plan.description||"No stated goal"}</span></div><div className="workout-plan-actions"><b>{plan.source}</b><button type="button" className="ghost pill-action" disabled={saving} onClick={()=>void removePlan(plan)}>Delete</button></div></header><ol>{plan.exercises.map(row=><li key={row.id}><span>{row.exercise.name}</span><small>{[row.sets&&`${row.sets} sets`,row.reps&&`${row.reps} reps`,row.weight_kg&&`${row.weight_kg} kg`,row.duration_seconds&&`${row.duration_seconds}s`].filter(Boolean).join(" · ")||"As needed"}</small></li>)}</ol></article>):<p className="muted">No plans saved yet.</p>}</div></section>
  </div>
}
