# Generated by Django 5.2.3 on 2026-08-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_connections', '0002_persistent_shell_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshmachine',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='sshmachine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='ssh_single_default_machine'),
        ),
    ]
